//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUPERSERVICE_MYHITOVA
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ClientService = new HashSet<ClientService>();
            this.Tag = new HashSet<Tag>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string GenderCode { get; set; }
        public string PhotoPath { get; set; }

        public string LastVisit
        {
            get
            {
                var clients = new List<ClientService> (MUHITOV_LANGUAGEEntities.GetContext().ClientService.ToList());
                clients = clients.Where(p => p.ClientID == this.ID).ToList();
                clients.Sort((a, b) => a.StartTime.CompareTo(b.StartTime));
                if (clients.Count() == 0)
                    return "Не было посещений";
                DateTime lastVisit = clients.First().StartTime;
                return lastVisit.Day.ToString() + "." + lastVisit.Month.ToString() + "." + lastVisit.Year.ToString();
            }
        }

        public int CountVisit
        {
            get
            {
                var clients = new List<ClientService>(MUHITOV_LANGUAGEEntities.GetContext().ClientService.ToList());
                clients = clients.Where(p => p.ClientID == this.ID).ToList();
                return clients.Count();
            }
        }

        public string GetGenderString()
        {
            return Gender.Name;
        }

        public string GetBirthday
        {
            get
            {
                return this.Birthday.Value.Day.ToString() + "." + this.Birthday.Value.Month.ToString() + "." + this.Birthday.Value.Year.ToString();
            }
        }

        public string GetReg
        {
            get
            {
                return this.RegistrationDate.Day.ToString() + "." + this.RegistrationDate.Month.ToString() + "." + this.RegistrationDate.Year.ToString();
            }
        }

        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientService> ClientService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tag { get; set; }
    }
}
